spring:
  datasource:
    url: jdbc:mysql://47.98.161.153/mmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: xikun@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

server:
  port: 8085
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true

ftp:
  address: 47.98.161.153
  port: 21
  username: ftpuser
  password: 123456
  uploadFile: /img
  imageBaseUrl: http://47.98.161.153:8070/img


logging:
  config:
