spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

server:
  port: 8080
  servlet:
    context-path: /

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true

ftp:
  address: 127.0.0.1
  port: 21
  username: xikun
  xikun: xikun
  bastPath: "F:\\upload"
  imageBaseUrl: ftp://192.168.205.61/img/


logging:
  config:
